// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IStatusCheckController is an autogenerated mock type for the IStatusCheckController type
type IStatusCheckController struct {
	mock.Mock
}

// Ping provides a mock function with given fields: c
func (_m *IStatusCheckController) Ping(c *gin.Context) {
	_m.Called(c)
}
